In [2]:
import sympy as sp
x,y=sp.symbols('x y')
f=x**2+2*y**2
grad=sp.Matrix([sp.diff(f,x),sp.diff(f,y)])
print(grad)

Matrix([[2*x], [4*y]])


In [3]:
import sympy as sp
x,y,z=sp.symbols('x y z')
f1=x**2+y*z
f2=y**2+x*z
f3=z**2+x*y
vec=sp.Matrix([x,y,z])
func=sp.Matrix([f1,f2,f3])
J=func.jacobian(vec)
print(J)

Matrix([[2*x, z, y], [z, 2*y, x], [y, x, 2*z]])


In [4]:
import numpy as np
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
eigenvalues,eigenvectors=np.linalg.eig(A)
print("Eigenvalues:")
print(eigenvalues)
print("Eigenvectors:")
print(eigenvectors)

Eigenvalues:
[ 1.61168440e+01 -1.11684397e+00 -3.38433605e-16]
Eigenvectors:
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [5]:
import numpy as np
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
U,s,Vt=np.linalg.svd(A)
print("Singular Values:")
print(s)
print("Left Singular vectors:")
print(U)
print("Right Singular Vectors:")
print(Vt)


Singular Values:
[1.68481034e+01 1.06836951e+00 3.33475287e-16]
Left Singular vectors:
[[-0.21483724  0.88723069  0.40824829]
 [-0.52058739  0.24964395 -0.81649658]
 [-0.82633754 -0.38794278  0.40824829]]
Right Singular Vectors:
[[-0.47967118 -0.57236779 -0.66506441]
 [-0.77669099 -0.07568647  0.62531805]
 [-0.40824829  0.81649658 -0.40824829]]
